name: Label Creator

on:
  workflow_dispatch:

jobs:
  create-labels:
    uses: PitchConnect/.github/.github/workflows/label-creator.yml@main
    permissions:
      issues: write
      contents: read
